import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '../globals.css';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { PropsWithChildren } from 'react';
import { NextUIProvider } from '@nextui-org/react';

import { cn } from '@/configs/cn';
import SideBar from '@/ui/molecules/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'relative h-full',
          process.env.NODE_ENV === 'development' && 'debug-screens'
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <NextUIProvider>
            <div className="flex h-dvh flex-[0_0_20%]">
              <SideBar />
              <div className="flex h-full w-full flex-1 flex-col bg-white">
                {children}
              </div>
            </div>
          </NextUIProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
